import type { Metadata } from "next";
import { Chewy } from "next/font/google";
import "./globals.css";

const chewySans = Chewy({
  variable: "--font-chewy-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${chewySans.variable} antialiased`}>{children}</body>
    </html>
  );
}
