import type { Metadata } from "next";
import { Chewy, DM_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const dmSans = DM_Sans({ subsets: ["latin"], variable: "--font-sans" });

const chewySans = Chewy({
  variable: "--font-chewy-sans",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans dark", dmSans.variable)}>
      <body className={`${chewySans.variable} antialiased`}>{children}</body>
    </html>
  );
}
