import type { Metadata } from "next";
import { use } from "react";
import { VerifyGameSession } from "@/game";
import { redirect } from "next/navigation";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: Readonly<React.ReactNode>;
  params: Promise<{ id: string }>;
}) {
  const param = use(params);
  const verification = use(VerifyGameSession(param.id));
  if (verification.status !== 200) {
    redirect("/");
  }
  return children;
}
